(function(){'use strict';var oh=function(a,b){return(a=a.A.filter(c=>c.Uc===b.Uc).map(c=>c.Jl))&&a.length?a[0]:OBR._jsc.mb(b)},ph=function(a){try{const b=JSON.parse(OBR.c.Z(OBR._jsc.B.ee,null));b&&(b.wl=b.wl.filter(c=>c.fx!==+a),b.wl&&(b.wl.length?OBR.c.za(OBR._jsc.B.ee,JSON.stringify(b)):OBR.c.Ed(OBR._jsc.B.ee)))}catch(b){OBR.logger.log("failed to delete Local Storage for skeleton")}},qh=function(a){OBR.logger.log(`[WARNING] ${a}`)},rh=function(a){var b=a.adInfo.cardIdx;const c=a.adInfo.fatherCardIdx,e=
a.adInfo.adPath,d=a.adInfo.adId,f=a.adInfo.adWidth,h=a.adInfo.adHeight,k=a.adInfo.adStyle;a.Ab=new OBR.Ab(M.ya(c));OBR.gptAds=OBR.gptAds||[];const g=M.createElement("script",null,null,{src:"//securepubads.g.doubleclick.net/tag/js/gpt.js"}),l=M.createElement("script",null,null,{type:"text/javascript"});l.appendChild(document.createTextNode(`
        window.googletag = window.googletag || {cmd: []};
        window.googletag.cmd.push(function () {
            var slot = window.googletag.defineSlot('${e}/${f}x${h}', [${f}, ${h}], '${d}');
            OBR.gptAds['${d}'] = slot;
            if(slot) {slot.addService(googletag.pubads())}
            window.googletag.pubads().enableSingleRequest();
            window.googletag.pubads().collapseEmptyDivs();
            window.googletag.pubads().setTargeting('publisher_id', []).setTargeting('variant_id', []).setTargeting('feed_id', []);
            window.googletag.pubads().addEventListener('slotRenderEnded', (event) => {
              var customEvent = new CustomEvent('${"onOBGptLoadedEvent"}', {detail: event});
              document.dispatchEvent(customEvent);
            })
            window.googletag.enableServices();
        });
    `));try{const m=M.createElement("div",d,`display:none;${k}`,{"class":a.className,"data-card-idx":b,"data-feed-father-idx":c});b=`window.googletag.cmd.push(function() { 
        window.googletag.display('${d}');
        window.googletag.pubads().refresh([OBR.gptAds['${d}']]);
      });`;document.head.appendChild(g);document.head.appendChild(l);const p=M.createElement("script",null,null,{type:"text/javascript"});p.appendChild(document.createTextNode(b));m.appendChild(p);a.Ab.Uo();document.addEventListener("onOBGptLoadedEvent",q=>{(q.detail||{empty:!0}).empty?(a.Ab.Po(),a.logger.error("createGPT failed - got an empty ad (event.detail.empty === true); check the ad settings"),m.style.display="none"):(m.style=`display:block; ${k}`,a.Ab.Vo())});return m}catch(m){a.logger.error(m),
a.Ab.Qo()}},sh=function(a){var b=a.adInfo.cardIdx;const c=a.adInfo.fatherCardIdx,e=a.adInfo.adPath,d=a.adInfo.adData,f=a.adInfo.adWidth,h=a.adInfo.adHeight,k=a.adInfo.adContainerWidth,g=a.adInfo.adContainerHeight;a.Ab=new OBR.Ab(M.ya(c));try{const l={"class":a.className,"data-card-idx":b,"data-feed-father-idx":c};(b=k||g?(k?`width:${k}px;`:"")+(g?`height:${g}px;`:"")+"display:none;":null)&&(l.style=b);const m=M.createElement("div",null,null,l),p=M.createElement("script",null,null,{src:"//securepubads.g.doubleclick.net/static/glade.js",
async:"true"}),q=M.createElement("div",null,"display: none;",{"data-glade":"","data-ad-unit-path":e,"data-json":d||"",width:f,height:h});m.appendChild(q);m.appendChild(p);a.Ab.Uo();q.addEventListener("gladeAdFetched",r=>{(r.detail||{empty:!0}).empty?(a.Ab.Po(),a.logger.error("createDFPAd failed - got an empty ad (event.detail.empty === true); check the ad settings"),q.style.display="none",m.style.display="none"):(q.style.display="block",m.style.display="block",a.Ab.Vo())});return m}catch(l){a.logger.error(l),
a.Ab.Qo()}},uh=function(){return th('<div class="ob-no-joker-card"></div>')},vh=function(a){var b=window.addEventListener?"addEventListener":"attachEvent";(0,window[b])("attachEvent"===b?"onmessage":"message",function(c){var e=c.message?"message":"data",d=c[e].message||c[e];"ob-pb-ad-loaded"===d?a.style.display="block":"ob-pb-ad-after-render"===d&&(a.style.height=`${c[e].data}px`)},!1)},wh=function({qd:a,Ea:b,ta:c,cardIdx:e,fatherCardIdx:d,IE:f,Mh:h,Nh:k,$g:g,Ti:l,vw:m,qb:p,os:q,Td:r,SA:v}){const t=
[];k&&t.push(`data-ob-installation-type=${k}`);l&&t.push(`data-ob-user-id=${l}`);g&&t.push(`data-ob-app-ver=${g}`);h&&t.push(`data-ob-installation-key=${h}`);m&&t.push(`data-click-url=${m}`);v&&t.push(`data-on-news=${v}`);r&&t.push(`data-pub-imp-id=${r}`);h=f&&f.includes("ob-gnr-layout");return th(`<div class="OUTBRAIN" data-src="${a}" data-widget-id="${b}" data-card-idx="${e}" data-feed-father-idx="${d}"
                            data-ob-mark="true" data-browser="${p}" data-os="${q}" data-dynload data-idx="${c}" id="outbrain_widget_${c}" ${t.join(" ")}>${h?"":f}</div>`)},Bh=function(a,b){var c=N.Oa();const {Ga:e,cardIdx:d}=a.ja(),f=M.ya(b);if(f)switch(e){case "widget":const {qb:k,os:g}=M.$(),{Ea:l,ta:m,html:p}=a.ja();return wh({qd:c,Ea:l,fatherCardIdx:b,ta:m,cardIdx:d,IE:p,Mh:f.bc(),Nh:f.cc(),$g:f.ac(),Ti:f.tb(),vw:f.mc(),SA:f.Fk(),qb:k,os:g,Td:f.fd()});case "joker":a=a.ja().bi;try{const K="string"===
typeof a?JSON.parse(a):a,H=xh[K.type](K,d,b);H.jokerProps=K;var h=H}catch(K){h=null}return h;case "adJoker":const {adType:q,adId:r,adWidth:v,adHeight:t,adPath:x,adData:u,adClient:w,adSlot:y,adContainerWidth:A,adContainerHeight:F,adStyle:J}=a.ja();return yh.create({adInfo:{cardIdx:d,fatherCardIdx:b,adType:q,adId:r,adWidth:v,adHeight:t,adPath:x,adData:u,adClient:w,adSlot:y,adContainerWidth:A,adContainerHeight:F,adStyle:J}});case "placeholderJoker":return{Dc:h}=a.ja(),zh.create({cardIdx:d,fatherCardIdx:b,
nF:h});case "passback":return{qB:h}=a.ja(),Ah.create(h,b)}},Dh=function(a){const b=Ch.find(c=>c.feedIdx===+a);return!(!b||!b.isSkeleton)},Gh=function(a,b){var c=OBR._jsc.nb();c=null!==c?c:{fb:{},wl:[]};const e={n:a.widgetName,r:0<a.height?a.height/a.width:0,fx:+b};a=c.wl.filter(d=>d.n===e.n&&0!==d.r).map(d=>{{const k=d.m?d.m+1:1;var f=d.r,h=e.r;d={n:d.n,m:k,r:k?1===k?(f+h)/2:((k-1)*f+h)/k:h,fx:+b}}return d})[0];c.fb.r=Eh(c,e);a=Fh(c,a,e);try{OBR.c.za(OBR._jsc.B.ee,JSON.stringify(a))}catch(d){OBR.logger.log("failed to set Local Storage for skeleton")}},
Eh=function(a,b){return a.wl&&a.wl.length?a.wl.reduce((c,e)=>c+e.r,0)/a.wl.length:b.r},Fh=function(a,b,c){a=Object.assign({},a);if(b&&b.n)return a.wl=a.wl.map(e=>e.n===b.n?b:e),a;c&&c.r&&a.wl.push(c);return a},R=function(a){return Math.min(...Object.keys(a.b))},Hh=function(a,b,c){a.b[b].hk=[];try{a.b[b].hk=JSON.parse(c).filter(e=>"widget"===e.type)}catch(e){}},Ih=function(a){var b=N;const c=b.b[a].$n,e=b.b[a].hk.splice(0,b.b[a].Gf);b.b[a].hk.push(...e.filter(d=>!c.find(f=>f.id===d.id)));return e},
Jh=function(a){N.j=a;OBR.lb.ph=a},Kh=function(a,b=R(a)){return a.b[b].Xo},Lh=function(a,b=R(a)){a.b[b].Xo=!0},Mh=function(a,b,{cardIdx:c}){var e=N;const {vf:d}=e.b[b];e.b[b]=Object.assign(e.b[b],{rc:c?c:0,Kd:a,vf:c?[...d,c]:d})},Nh=function(a=0,b){if(a=N.b[a])a.nr=b},Oh=function(a){var b=N;if(a)return b.b[a].rc},Ph=function(a,b){({vf:a}=N.b[a]);return-1<a.indexOf(b)},Qh=function(a,b){var c=N;const {vf:e}=c.b[a];c.b[a].vf=e.filter(d=>d!=b)},Rh=function(a){return N.b[a]||{}},Sh=function(a,b=R(a)){return a.b[b].Wo},
Th=function(a,b,c=R(a)){a.b[c].Wo=b},Uh=function(a,b,c,e=R(a)){a.b[e].Io[b]=c},Vh=function(a,b,c=R(a)){a.b[c].si=b},Wh=function(a,b=R(a)){return a.b[b].si},Xh=function(a,b,c=R(a)){return a.b[c].Io[b]},Yh=function(a,b,c=R(a)){a.b[c].Jo=b},Zh=function(a,b=R(a)){return a.b[b].Jo},$h=function(a,b,c=R(a)){a.b[c].De=b},ai=function(a,b=R(a)){return a.b[b].De},bi=function(a,b=R(a)){a.b[b].$h=!0},ci=function(a,b=R(a),c,e){!c||OBR.na.kb||OBR.na.rb||(a.b[b].Uj=c,"1"!==e&&1!==e)||(a.b[b].lo=1)},di=function(a,
b=R(a)){return a.b[b].Uj?{consentString:a.b[b].Uj,consentVersion:a.b[b].lo}:null},ei=function(a,b,c){a.b[b].fa.hl=c},V=function(a,b,c){fi(a,b&&"undefined"!==typeof c&&null!=c&&""!==c?`${b}=${c}`:"")},gi=function(a,b,c){try{const e=(new URLSearchParams(window.location.search)).get(b);e&&(c=e)}catch(e){}c&&V(a,b,c);return a},fi=function(a,b){if(b){const c=a.b;c.endsWith("&")||c.endsWith("?")||b.startsWith("&")?a.b+=b:a.b+=`&${b}`}},li=function(a=0,b=0){var c=OBR.I.length-1;if(!N.b[a])return Promise.resolve();
const e=M.ya(a);var d=Wh(N,a);if(d)var f=(new hi(M,d)).s();else{a=new ii(M,a,b,c);a.qd&&a.qd.startsWith("http")||ji.error("could not get permalink url");V(a,"url",OBR.c.oa(a.qd));c=a.i.J();V(a,"widgetJSId",a.V.$().Pb&&a.V.$().Pb[c]?a.V.$().Pb[c]:c);a.V.$().Pb&&a.V.$().Pb[c]&&V(a,"contextRule",!1);V(a,"version",a.V.$().ver);V(a,"apv",a.V.$().pf);V(a,"sig",a.V.$().Xm);V(a,"format",a.i.pp());V(a,"rand",OBR.c.rand());(c=a.V.Z(OBR._jsc.B.zj))&&V(a,"lsd",OBR.c.oa(c));(c=a.V.Z(OBR._jsc.B.Aj))&&V(a,"lsdt",
OBR.c.oa(c));(c=OBR.cf.Tm)&&V(a,"odlsd",c);a.i.Sh()&&V(a,"em","1");c=a.V.$().rg;null!==c&&V(a,"pubInState",c);(c=a.V.$().pi)&&V(a,"osLang",c);a=gi(a,"obAbtest",a.V.R("obAbtest",""));(c=!0===a.V.$().Ni||!0===a.i.Fh()||null!==a.V.$().Pb)&&V(a,"testMode",c);V(a,"videoId",a.i.Lk());OBR.g.nf&&OBR._jsc.lf()&&V(a,"opvid",OBR._jsc.lf());c=a.i.ub()||a.V.$().fk||"";V(a,"extid",c);{const [h,k]=OBR._jsc.kf(a.i);V(a,h,k)}(!0===a.i.rq()||a.V.$().Rl)&&V(a,"rtbEnabled",!0);c=a.i.Eh();V(a,"seid",encodeURIComponent(c));
a.V.$().vo.includes("true")&&V(a,"descriptionDisplayEnabled",!0);a.V.$().tq.includes("true")&&V(a,"isRtbDescriptionEnabled",!0);V(a,"va",!0===a.i.Cq()?!0:null);V(a,"et",!0===a.i.lp()?!0:null);(c=a.V.$().jp())&&V(a,"contxtKV",OBR.c.oa(c));V(a,"cnsnt",OBR.na.kb);V(a,"cmpStat",OBR.na.lc?1:0);V(a,"cnsntv2",OBR.na.rb);(c=di(N,a.Ib))&&(1===c.consentVersion?V(a,"cnsnt",c.consentString):V(a,"cnsntv2",c.consentString));V(a,"ccpa",a.i.rk()||OBR.na.kc);V(a,"ccpaStat",OBR.na.cl?1:0);V(a,"num",null!==a.i.Ch()?
a.i.Ch():null);a.i.Qb()||(c=a.i.Dp(),null!==c&&"string"===typeof c&&0<c.length?V(a,"srcUrl",OBR.c.oa(c)):0<a.V.$().Ki.length&&V(a,"srcUrl",a.V.$().Ki));c=a.V.$().nm;V(a,"scrW",c.w);V(a,"scrH",c.h);c=a.V.$();c=a.i.Qb()?c.hm:c.Lm;fi(a,""!==c?"t="+c:"t");(c=a.V.$().gk)&&V(a,"xp",OBR.c.oa(c));c=OBR.ga.Qa;V(a,"winW",c.width);V(a,"winH",c.height);V(a,"adblck",OBR.g.kh.Gh()||!0===a.V.Zf()?"true":"false");V(a,"abwl",a.V.Ph());(c="https://"===a.V.$().xa)&&V(a,"secured",c);V(a,"feedIdx",a.Ib);V(a,"lastIdx",
a.vA);V(a,"lastCardIdx",a.rc);a.V.$().qo.includes("true")&&V(a,"crDraft",!0);(c=a.V.ed(a.Ib))&&V(a,"fAB",c);(c=a.V.zk(a.Ib))&&V(a,"layeredTestInfo",c);OBR.g.cq&&V(a,"wrDebug","true");V(a,"app_ver",a.i.ac());V(a,"api_user_id",a.i.tb());V(a,"installationType",a.i.cc());a.V.$().kd&&V(a,"iframe","true");(c=a.V.$().md)&&V(a,"lscntx",c);a.V.R("obFakeRtb",!1)&&(V(a,"fakeRec","RTB-CriteoUS"),V(a,"fakeRecSize","4"));c=OBR.fraudDetection;!0!==a.V.$().Ni&&!0!==a.i.Fh()&&((d=c.Cd||c.rm)?V(a,"clss",d):c.Ke&&(V(a,
"clid",c.Ke),V(a,"fdu",c.nh)));c=a.V.$().Cm;null!==c&&V(a,"skipContextValidation",c);c=a.V.$().nk;null!==c&&V(a,"forceContextValidation",c);(c=a.V.$().Hi)&&V(a,"skipRecsFilters",`${c}`);if(c=a.V.$().th)V(a,"forceAd",c),V(a,"settingLevel","SOURCE");(c=a.V.$().pk)&&V(a,"forceOcAd",c);V(a,"dpr",a.V.$().bk||0);c=a.i.Kf();V(a,"cw",c);({ii:c}=a.V.$());c||V(a,"wdr-natlaz",!1);a.V.$().Dm&&V(a,"wdr-ads-data","true");(c=OBR._jsc.Af())&&fi(a,c);a=gi(a,"forceDemand",a.V.$().$o);(c=a.V.$().Ri||null)&&V(a,"trace_name",
c);if(a.V.$.sc&&(c=a.i.dd()))try{f=(new window.URLSearchParams(c)).get("appBridge"),V(a,"appBridge",f)}catch(h){}({Ql:f}=a.V.$());f&&V(a,"ob_internal_id",f);(f=OBR.c.Cg(a.i.fd()||OBR.g.Td))&&V(a,"pubImpId",f);OBR.g.ki&&V(a,"dicbo",OBR.g.ki);V(a,"iabCat",a.i.Ah());OBR._jsc.Df&&V(a,"id5",OBR._jsc.Df.Ps);OBR._jsc.Df&&V(a,"id5type",OBR._jsc.Df.Jq);V(a,"activeTab",!document.hidden);OBR.g.eq&&V(a,"lsl","1");({gr:f}=a.V.$());f&&V(a,"wdr-lr","1");(f=a.V.$().lm)&&V(a,"ref",f);f=OBR.c.Cg(a.i.fd()||OBR.g.Td);
V(a,"pubImpId",encodeURIComponent(f));OBR.g.oi&&V(a,"ogn",OBR.g.oi);f=a.i.dd();a.V.$().sc&&f&&fi(a,f);f=a;(a=f.i.Rf())&&V(f,"rw",a);f=f.j();fi(f,OBR._jsc.dc(f.i));V(f,"chs",OBR.g.tk(f.i));f=f.s()}return ki(e,f,b)},mi=function(a){return Array(Math.min(a.s,3)).fill(Math.round(100*a.b.fb.r)/100)},ni=function(a,b){return a.b?a.b.wl.filter(c=>0!==+c.r).map(c=>{if(b.find(e=>e.id===c.n))return Math.min(Math.round(100*+c.r)/100,1)}).filter(c=>c):null},oi=function(a){if(a.s&&a.b&&Array.isArray(a.b.wl)&&a.b.wl.length&&
a.b.fb.r)return"local-storage";const b=a.Qd.J();return a.j&&Array.isArray(a.j)&&a.j.some(c=>c.includes(b))?"cheetah":"none"},pi=function(a){const b=N.b[a.Ib].Gf,c=(d,f)=>d.length<b?(d.push(...f),c(d,[...f])):d.splice(0,b);if("2"===N.re(a.Ib))return mi(a);var e=Ih(a.Ib);if(!e.length)return null;(e=ni(a,e))&&e.length&&e.length<b&&(e=c(e,[...e]));return e?e:mi(a)},qi=function(a){a.Qd.Rm()||ph(a.Ib);switch(oi(a)){case "local-storage":return pi(a);case "cheetah":OBR._jsc.vb.remove(a.Qd,!0);var b=OBR._jsc.rb(OBR._jsc.vb,
a.Qd.J());b?([,b]=b,a=a.A?Array(1).fill(b):Array(a.s).fill(b)):a=null;return a;case "none":return null;default:return null}},ui=function(a,{Qd:b,Ko:c=!1}){const e=b.L();if(!N.b[e])if(b.B()){var d=b.B();d=1===d.children.length&&0===d.children[0].children.length;a.hd=d;N.b[e]={Wo:!0,Xo:!1,rc:0,vf:[0],Io:{Ko:!1,sF:!1},Jo:null,si:null,De:!1,$h:!1,nr:null,Uj:null,lo:2,Gf:null,Pn:!0,Yh:!1,fa:{hl:!1},Pl:0};{d=[];const f=b.l("feedWrapperMargins",""),h=b.Kf();f&&d.push(`margin:${f}`);b.l("hideHeaders",!1)&&
M.pa(".ob-smartfeed-wrapper .OUTBRAIN:not(:first-child):not(.ob-parent-feed) .ob-widget-header {display:none;}");0===h&&d.push("width:100%");M.pa(".ob-smartfeed-wrapper .OUTBRAIN:not(:first-child):not(.ob-parent-feed) .ob_what {display:none;} "+`.ob-smartfeed-joker {margin-bottom: 20px; padding-bottom: 4px; padding-top: 0;} ${d.length?`.ob-smartfeed-wrapper.feedIdx-${b.L()} {${d.join(";")}}`:""}`)}if(d=b.mc())Yh(N,d,b.L()),M.Xg(b);d=b.l("recMode");Uh(N,"feedManualChunkFetch",c,e);Uh(N,"feedLayout",
"odb_dynamic_feed"===d,e);Xh(N,"feedManualChunkFetch",e)?(ri(b),OBR.g.sc&&si(a,e)):(!0===b.l("lazyLoadFirstCycle",!1)?(c=b.B(),d=b.l("lazyLoadFirstCycleMargin",250)+"px",a={callback:a.j.bind(a),callbackParams:[b],element:c,rootMargin:d,threshold:[0],unobserve:!0},(new OBR.IntersectionObserver(a)).observe()):a.j(b),ti.Ne(b,e))}else qh(`Container for widgetId=${b.J()} doesn't exist on the DOM. Feed cannot be created.`)},ri=function(a){const b=a.L();(a.Hd()||a.Id()||a.Jd())&&(a=a.ka("nextFeedUrl"))&&
Vh(N,a,b)},vi=function(a,b){var c=Number(b.l("loadExtraChunksOnStart",0));N.b[a].Pl=c;c=b.l("feedLoadChunkSize",0);N.b[a].Gf=c?1*c:null;Hh(N,a,b.l("feedContent","[]"));c=N;var e=b.l("feedCardsRunningOnce","[]");c.b[a].$n=[];try{c.b[a].$n=JSON.parse(e)}catch(d){}N.um(a,b.u("feedVersion","1"));c=b.l("intersectionObserverTriggerMargin","0");N.b[a].gz=c;N.Fi(b.Oa());ci(N,a,b.wh(),b.vk())},Bi=function(a,b,c,e=null){const {rc:d,Kd:f}=Rh(b);var h=M.ya(b);try{var k=OBR.g.Un&&OBR.g.Un.feedIdx===parseInt(b)}catch(g){k=
!1}k?wi(h,b):(k=0===c&&h.Ak(),!1===f?(qh("fetchNextStream was triggered with hasMore=false. aborting..."),xi(e,"grey")):Ph(b,c)?(OBR.controller.pv(b),xi(e,"green"),e=h.J(),Qh(b,c),c=a.s(b,e),(e=yi(b))&&e.appendChild(c),k?zi(a,h.Ak(),b):(h=N.j.then(()=>li(b,d)),Jh(h),h.then(a.b.bind(a)).catch(g=>Ai(g,b)))):(ji.log("fetchNextStream was triggered but chunk is not observered. aborting..."),xi(e,"red")))},wi=function(a,b){const c=N.b[b].fa;c.hl||((new OBR.K(a,e=>e.tt)).G.gt.D(),ei(N,b,Object.assign(c,
{hl:!0})))},xi=function(a,b){OBR.g.li&&a&&(a.style.outline=`3px dashed ${b}`)},yi=function(a){const b=Xh(N,"feedLayout",a);return Ci(a,b)},zi=function(a,b,c){const {rc:e}=Rh(c);c=M.ya(c);const d=parseInt(performance.now());b.Du={ra:c.J(),ta:e,timestamp:d};a.b(b)},Ai=function(a,b){OBR.error(a);ji.error(`failed on Multivac response on feedIdx:${b}. Reason: ${a.toString()}`);Di();Jh(Promise.resolve())},Fi=function(a,b){const {rc:c,Kd:e,Yh:d}=Rh(b);if(!d&&!1!==e){var f=M.ya(b).Ak();Qh(b,-1);f&&0===c?
zi(a,f,b):(Ei(yi(b)),f=N.j.then(()=>li(b,c)),Jh(f),N.b[b].Yh=!0,f.then(h=>{N.b[b].Yh=!1;a.b(h)}).catch(h=>{N.b[b].Yh=!1;Ai(h,b)}))}},Gi=function(a,b){return b&&b.tl()&&b.eg()&&a.A},Hi=function(a,b,c,e){return Gi(a,b)?(a.A=!1,c.forEach(d=>{const {ta:f}=d.ja();d.da=()=>b;OBR.I[f]=d}),OBR.controller.Bx().add(`widgetLazyRender_${b.L()}`,()=>{a.b(e,!0)}),!0):!1},Ii=function(a,b,c){return b.map(e=>Bh(e,c),a)},Ji=function(a){if(OBR.g.li){const b=OBR.c.ky();a.forEach(c=>c.style.boxShadow=`-2px 4px 10px 2px ${b}`)}},
Ki=function(a,b,c){a.forEach(e=>{const d=e.ja().ta;{var f=N.Oa(),h=Zh(N,b);var k=M.ya(b);const {ta:g,Ea:l,AB:m}=e.ja();e=m&&m.response&&m.response.request&&m.response.request.kG;f={permalink:f,widgetId:l,feedFatherIdx:b,idx:g,clickTrackerUrl:h,extId:k.ub(),extId2:k.nc()};const p=OBR.Yd.Xj(f);p.setData(m);p.$r(b);p.us();f=p;k&&(h=k.dd(),(k=k.tb())&&f.Vr(k),h&&f.sm(h));e&&p.ym(e);k=OBR.I[g]=p}OBR.controller.ms(k);k.ps(c);OBR.controller.To(k,d);k.Wr();M.qg(k);M.Ie(k);OBR.controller.Pk(k);OBR.controller.Bc(d);
ti.Ne(k,b)})},Li=function(a,b,c){const e=N.b[b].Pl;0<e?(Bi(a,b,Rh(b).rc),N.b[b].Pl=e-1):c&&c.length&&c.forEach(d=>d&&a.Sl(b,d.ja()))},Mi=function(a){return!a||0===a.length||a.map(b=>M.ya(b.ja().ta)).every(b=>!b.Ja())},Ni=function(a,b){Mh(!0,b,{cardIdx:parseInt(Oh(b))+parseInt(N.b[b].Gf)});Bi(a,b,Oh(b))},Oi=function(a){a.filter(b=>{b=M.ya(b.ja().ta);return b.Kc()&&!b.Uh()}).forEach(b=>{var c=M.B(b.ja().ta),e=b.ja().Ea;b=M.ya(b.ja().ta);if(c&&!c.shadowRoot){var d=e.includes("REEL");e=c.querySelector(".ob-widget");
d&&(d=document.createElement("div"),d.appendChild(e),e=d);e&&c.attachShadow&&(d=b.xh(),b=b.Lf(),OBR.c.attachShadow(c,e,{mode:"open"},d,b))}})},Pi=function(a,b){a.filter(c=>c.ja().Dc).map(c=>{try{const e=c.ja().cardIdx,d=c.ja().Dc.split(".").reduce((h,k)=>h[k],window),f=yi(b).querySelector(`div[data-card-idx='${e}']`);d&&f&&setTimeout(d.bind(null,f),0)}catch(e){ji.error(`fail to run card callback, card Json: ${c.ja()} error: ${e}`)}})},si=function(a,b=R(N)){if(M.ya(b)){vi(b,M.ya(b));if(Xh(N,"feedManualChunkFetch",
b))return Fi(a,b),!0;qh("externalChunkLoad called but feed is not set for external chunk fetching");return!1}qh(`externalChunkLoad called but feedIdx=${b} not found`);return!1},Qi=function(a,b){return a.filter((c,e)=>b[e].style.opacity)},Ri=function(a){return a.filter(b=>b.style.opacity)},Si=function(a,b){const c=[],e=a.filter(d=>"widget"===d.ja().Ga);b.forEach(d=>e.forEach(f=>{const h=d.attributes["data-card-idx"].value,k=f.ja().cardIdx;if(h===k)return c.push(f)}));return c};
OBR.Ab||function(){class a{constructor(b){this.i=b;this.K=new OBR.K(this.i,c=>c.nt);this.j={}}Uo(){OBR.logger.log("[DFP Data] glade DFP ad requested");this.b({event:this.K.G.Zt,data:this.j})}Vo(){OBR.logger.log("[DFP Data] glade DFP ad served");this.b({event:this.K.G.bu,data:this.j})}Po(){OBR.logger.log("[DFP Data] glade DFP got empty ad");this.b({event:this.K.G.EMPTY,data:this.j})}Qo(){OBR.logger.log("[DFP Data] glade DFP got error");this.b({event:this.K.rt,data:this.j})}b(b){b.event.D(b.data)}}
return OBR.Ab=a}();const ji={error(a){OBR.logger.log(`[ERROR] ${a}`)},log(a){OBR.logger.log(a)}};const Ti=new OBR.Mb,M={Hf(a,b){Ti.D("afterRender",[b],!1,a)},qg(a){OBR.controller.qg(a)},Ie(a){OBR.controller.Ie(a)},createElement(a,b,c,e){return OBR.c.createElement(a,b,c,e)},pa(a){OBR.c.pa(a)},B(a){return OBR.c.B(a)},ed(a){if(a=OBR.I[a])return a.u("abTestVal",null)},zk(a){return(a=OBR.I[a])?a.u("layeredTestInfo",null):null},R(a,b){return OBR.c.R(a,b)},Kf(a){if(a=OBR.I[a])return a.Kf()},ya(a){return OBR.I[a]},Xg(a){return OBR.controller.Xg(a)},Z(a){return OBR.c.Z(a,null)},yF(){return OBR.controller},
$(){return OBR.g},Zf(){return"true"===OBR.Eb.Zf()},Ph(){return"true"===OBR.Eb.Ph()},Sl(a,b,c={}){const e=a&&a.getAttribute("id")?[a.getAttribute("id").substr(16)]:[];(new OBR.IntersectionObserver(Object.assign({element:a,callback:b,threshold:[0],unobserve:!0,callbackParams:e},c))).observe()},S(a,b){OBR.o.S(a,b)}};const th=a=>{const b=document.createElement("div");b.innerHTML=a;return b.firstChild},Ci=(a,b=!1)=>{if(a=M.B(a))return b?OBR.c.N(a).querySelector(".ob-cards"):a.parentNode},Ui=(a=!1,b,c)=>{const e=document.createDocumentFragment();c.forEach(d=>d&&e.appendChild(d));(a=Ci(b,a))&&a.appendChild(e)},Vi=(a,b,c)=>{let e=!0;const d=1.1*b;c.forEach(f=>{f.style.opacity=0;a.appendChild(f);a.scrollHeight<=d?f.style.opacity=1:(e=!1,f.parentNode.removeChild(f))});return e},Wi=(a=!1,b,c)=>{const e=document.createDocumentFragment();
e.appendChild(c);(a=Ci(b,a))&&a.appendChild(e)},Ei=a=>{var b=OBR._jsc.mb();a&&a.appendChild(b)},Di=a=>{var b=a&&a.J();b=`.ob_sf_loader, ${b?`.${b}`:""}.ob-chunks-loader`;if(a&&(a=(a=(a=a.B())&&a.parentNode&&a.parentNode.querySelectorAll(b))&&Array.from(a))&&a.length&&null!==a[0].parentNode){for(b=0;b<a.length;b++){const c=a[b];c.parentNode.removeChild(c)}return}(b=document.querySelector(b))&&null!==b.parentNode&&b.parentNode.removeChild(b)},Xi=(a=0)=>{(a=M.ya(a))&&(a=a.B())&&a.style.removeProperty("visibility")};var Yi=class{constructor(){this.className="ob-smartfeed-adjoker";this.adInfo={};this.logger=ji}create({adInfo:a}){this.adInfo=a;if(a.adType)switch(a.adType.toLowerCase()){case "gpt":return rh(this);case "dfp":return sh(this);case "adsense":a:{try{var b=this.adInfo.cardIdx,c=this.adInfo.adClient,e=this.adInfo.adSlot,d=`ad-unit-/${b}`,f=M.createElement("div",d,null,{"data-card-idx":b,"data-feed-father-idx":this.adInfo.fatherCardIdx}),h=M.createElement("script",null,null,{src:"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
async:"true"}),k=M.createElement("ins",null,"display:inline-block;width:100%;height:200px",{"class":`${this.className} adsbygoogle`,"data-ad-client":c,"data-ad-slot":e}),g=M.createElement("script",null,null,null);g.innerText=`googletag.cmd.push(function() {googletag.display('${d}')\;})`;f.appendChild(h);f.appendChild(k);f.appendChild(g);var l=f;break a}catch(m){this.logger.error(m)}l=void 0}return l;case "gptframe":case "pb":a:{l=this.adInfo.cardIdx;b=this.adInfo.fatherCardIdx;c=this.adInfo.adId;
e=this.adInfo.adPath;f=this.adInfo.adType;h=this.adInfo.adWidth;k=this.adInfo.adHeight;a=M.ya(b);g=a.u("abTestVal");a=a.u("pid");try{const m=`thirdPartyType=${f}&thirdPartyId=${c}&adPath=${e}&width=${h}&height=${k}&refferer=${window.location.host}&pubId=${a}&abTestVal=${g}&feedIdx=${b}`,p=M.createElement("div",null,"position: relative; height: 120vw; margin: auto; max-width: 640px; max-height: 499px; display: none",{"class":this.className,"data-card-idx":l,"data-feed-father-idx":b}),q=M.createElement("iframe",
null,"position: absolute; top: 0; left : 0; height: 100%; width: 100%; border: 0;",{src:`${OBR.g.xa}widgets.outbrain.com/nanoWidget/externals/ob3rdPFrame/ob3rdPFrame.htm?${m}`});vh(p);p.appendChild(q);d=p;break a}catch(m){this.logger.error(m)}d=void 0}return d;default:return a?this.logger.error(`adJoker type is of unknown type: ${a.adType}`):this.logger.error(`adJoker information object is ${a}`),uh()}qh(`adJoker could not be created ${a}`);return uh()}};const yh=new Yi;var Zi=class{create({cardIdx:a,fatherCardIdx:b}){try{return M.createElement("div",null,null,{"class":"ob-smartfeed-joker","data-card-idx":a,"data-feed-father-idx":b,"data-joker-placeholder":""})}catch(c){return ji.error(`joker placeholder failed. error: ${c}`),th('<div class="ob-no-joker-card"></div>')}}};const zh=new Zi;var $i=class{create({cardIdx:a,fatherCardIdx:b,bi:c}){a=M.createElement("div",null,null,{"class":"ob-smartfeed-joker","data-card-idx":a,"data-feed-father-idx":b});c=c.selector;b=document.querySelector(c);if(null!==b)return b.parentNode.removeChild(b),b.style.display="block",a.appendChild(b),a;ji.error(`joker failed - '${c}'`);return th('<div class="ob-no-joker-card"></div>')}};const aj=new $i;const xh={joker:(a,b,c)=>{if(!a)ji.error(`JokerCard failed - '${a.selector}'`);else if(a&&a.selector){const e=document.querySelector(a.selector);e?e.style.display="none":ji.error(`JokerCard failed joker selector was not found on page - selector: '${a.selector}'`)}return aj.create({cardIdx:b,fatherCardIdx:c,bi:a})},adJoker:(a,b,c)=>yh.create({adInfo:{cardIdx:b,fatherCardIdx:c,adType:a.adType,adId:a.adId,adWidth:a.adWidth,adHeight:a.adHeight,adPath:a.adPath,adData:a.adData,adClient:a.adClient,adSlot:a.adSlot,
adContainerWidth:a.adContainerWidth,adContainerHeight:a.adContainerHeight,adStyle:a.adStyle}}),placeholderJoker:(a,b,c)=>zh.create({cardIdx:b,fatherCardIdx:c})};var bj=class{create(a,b){try{a:{var c=M.ya(b);try{if(c){var e=c.l("passbackTagSize","300x250").split("x");break a}}catch(g){}e=[300,250]}const [d,f]=e,h=Ci(b,!1),k=document.createElement("iframe");k.style.height=`${f}px`;k.style.width=`${d}px`;k.style.border="0";h.parentNode.insertBefore(k,h.nextSibling);h.style.display="none";k.contentWindow.document.open();k.contentWindow.document.write(`
      <style> body {margin: 0;padding: 0;border: 0;font-size: 100%;font: inherit;vertical-align: baseline;}</style>
      <script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
      <div id="gpt-passback">
        <script>
          window.googletag = window.googletag || {cmd: []};
          googletag.cmd.push(function() {
              googletag.defineSlot('${a}', [${d}, ${f}], 'gpt-passback')
                .addService(googletag.pubads());
              googletag.enableServices();
              googletag.display('gpt-passback');
          });
        </script>
      </div>`);k.contentWindow.document.close()}catch(d){OBR.logger.log(d)}return th('<div class="passback-tag"></div>')}};const Ah=new bj;const Ch=[];
var cj=class{constructor(){}C(a,b){b=parseInt(b,10);this.ec=a.ec();a.Rm()&&a.Pa()&&Ch.push({feedIdx:b,isSkeleton:!0});a=1*OBR.c.Z("debug-widget-stats-sample",1E5);this.A=a=1>Math.floor(Math.random()*a)}Ne(a,b){try{if(this.C(a,b),this.ec){var c=Dh(b);{const t={};if(c||this.A){{const x=a.B(),u=window.getComputedStyle(x),w=x.offsetWidth,y=x.offsetHeight;var e={width:w,height:y,outerWidth:w+parseInt(u.marginLeft,10)+parseInt(u.marginRight,10),outerHeight:y+parseInt(u.marginTop,10)+parseInt(u.marginBottom,10)}}var {width:d,
height:f,outerWidth:h,outerHeight:k}=e,g=window.OB_releaseVer,l=OBR.monitorData,m=OBR.env;t.name="obm-WidgetDimensions";t.version=g;t.env=m||1;var p={widgetName:a.J(),widgetId:a.u("wnid",a.J()),screenWidth:window.innerWidth,screenHeight:window.innerHeight,width:d,height:f,outerWidth:h,outerHeight:k,platform:a.u("readerPlatform","desktop"),feedVersion:a.u("feedVersion")||"1"};t.url=location.href;t.agent=navigator.userAgent.toLowerCase();l&&(t.sId=l.sourceId,t.dId=l.docId,t.pId=l.pubId);var q={fc:t,
Go:p}}else q={fc:t,Go:{}}}var {fc:r,Go:v}=q;if(this.A){{const t=`${OBR.g.Wi}/WidgetErrorMonitor/api/report`;r.extra=JSON.stringify(v);OBR.Ua.get(t,r)}}c&&Gh(v,b)}}catch(t){OBR.error({name:"SetSkeletonError",message:"Could not set skeleton values",e:t})}}};const ti=new cj;var dj=class{constructor(){this.C()}C(){this.b={};this.j=Promise.resolve();this.qd=null}um(a,b){this.b[a].gx=b}re(a){return this.b[a].gx}Oa(){return this.qd}Fi(a){this.qd=a}$h(a=R(this)){return this.b[a].$h}};const N=new dj;var hi=class{constructor(a,b){this.b=b}s(){return this.b}};var ii=class{constructor(a,b,c,e){this.V=a;this.b=`${this.V.$().Xq}/Multivac/api/get?`;this.i=a.ya(b);this.Ib=b;this.rc=c;this.vA=e;this.qd=this.i.Oa()}j(){fi(this,OBR._jsc.cc.j());return this}s(){return this.b}};const ki=(a,b,c)=>{const e=parseInt(performance.now());OBR._jsc.Rb.mark(a,"mv","start",!0);return new Promise((d,f)=>{const h=document.createElement("script");h.src=b;h.onerror=function(){f({name:"multivac",message:"multivac call failed"});OBR.c.ug(h)};OBR.extern.returnedVacData=k=>{k.Du={ra:a.J(),ta:c,timestamp:e};const g=OBR._jsc.Gf.b.stop().getTime();a.TC(g);d(k);OBR.c.ug(h)};document.body.appendChild(h);OBR._jsc.Gf.b.start()})};var ej=class{constructor(a){this.response=a;this.b=a.cards.map(b=>{switch(b.cardType){case "widget":return new fj(b);case "joker":return new gj(b);case "adJoker":return new hj(b);case "placeholderJoker":return new ij(b);case "passback":return new jj(b);default:ji.error(`card type "${b.cardType}" is not supported`)}}).filter(b=>void 0!==b)}ja(){const a=this.b.filter(b=>"widget"===b.ja().Ga);return{Vm:a,Ib:this.response.feedIdx,Kd:this.response.hasMore,bh:this.b,ze:this.b[this.b.length-1],Dv:[a[0],
a[a.length-1]],si:this.response.nextFeedURL}}};var fj=class{constructor(a){this.ia=a}ja(){return{Ga:this.ia.cardType,AB:this.ia,html:this.ia.response.html,Ea:this.ia.response.request.widgetJsId,ta:this.ia.response.request.idx,cardIdx:this.ia.response.request.fCard}}};var ij=class{constructor(a){this.ia=a}ja(){return{Ga:this.ia.cardType,bi:this.ia.response,cardIdx:this.ia.fCard,Dc:this.ia.response.callback}}};var jj=class{constructor(a){this.ia=a}ja(){return{Ga:this.ia.cardType,qB:this.ia.passbackCode}}};
var gj=class{constructor(a){this.ia=a}ja(){return{Ga:this.ia.cardType,bi:this.ia.response,cardIdx:this.ia.fCard}}};
var hj=class{constructor(a){this.ia=a}ja(){return{Ga:this.ia.cardType,adId:this.ia.response.adId,adWidth:this.ia.response.adWidth,adHeight:this.ia.response.adHeight,adPath:this.ia.response.adPath,adData:this.ia.response.adData,adClient:this.ia.response.adClient,adSlot:this.ia.response.adSlot,adType:this.ia.response.adType,adContainerWidth:this.ia.response.adContainerWidth,adContainerHeight:this.ia.response.adContainerHeight,cardIdx:this.ia.fCard,adStyle:this.ia.response.adStyle}}};var kj=class{constructor(a,b){this.Ib=a;this.A=b;this.j=OBR._jsc.ob(OBR._jsc.vb);this.b=OBR._jsc.nb();this.s=N.b[a].Gf;this.Qd=M.ya(a)}};const lj=(a,b=!1)=>qi(new kj(a,b));var mj=class{constructor(){this.A=!0}j(a){const b=a.L(),c=M.ya(b);Kh(N,b)||(Lh(N,b),ri(a),vi(b,c),M.$().Fq||Bi(this,b,0))}s(a,b){a={uf:lj(a),Uc:b};b=OBR._jsc.vb;try{if(a.uf){b.s=OBR._jsc.nb();var c=b.s?OBR._jsc.mb(a):oh(b,a)}else c=OBR._jsc.mb()}catch(e){c=OBR._jsc.mb(a)}return c}b(a){if(a){var b=(new ej(a)).ja(),c=b.bh,e=b.Ib,d=b.Dv,f=b.si;if(N.b[e]){var {Vm:h,ze:k}=b,[g,l,m]=[M.ya(e),!Xh(N,"feedManualChunkFetch",e),Xh(N,"feedLayout",e)];b=JSON.parse(b.Kd);if(g&&(g.Zr(c.length),OBR._jsc.Rb.mark(g,
"mv","end",!0),!Hi(this,g,h,a)&&(Di(g),Xi(e),f&&Vh(N,f,e),c&&0!==c.length?a=!1:(b&&Ni(this,e),a=!0),!a))){var p=Ii(this,c,e);{var q=h;a=k;f=b;const [t,x,u]=["2"===N.re(e),g.op(),Xh(N,"feedLayout",e)];if(t&&x){b=q;{q=g.op();var r=b,v=p;const w=1.1*q,y=Ci(e,Xh(N,"feedLayout",e));let A=null;M.pa(`.ob-feed-${e}-max-height {max-height: ${w}px; overflow: hidden;}`);OBR.c.ma(y,`ob-feed-${e}-max-height`);Vi(y,q,v)||(A={Vm:Qi(r,v),Kd:!1,Cv:Ri(v)});OBR.c.Ha(y,`ob-feed-${e}-max-height`);q=A}q&&(b=q.Vm,a=b.slice(-1)[0],
f=q.Kd,p=q.Cv);[q,a,f,p]=[b,a,f,p]}else Ui(u,e,p);b=[q,a,f,p]}[h,k,b,p]=b;Ji(p);Ki(h,e,g.Kx());this.Bc(c,h,e);b||(a=p[p.length-1],OBR.Lg.D(`onFeedEnd_${e}`,[a,OBR.c.N(a).querySelector(".ob-dynamic-rec-container:last-child")],!0,g));Mh(b,e,k.ja());l&&b&&Li(this,e,d);1===c.length&&c[0].ia&&"joker"===c[0].ia.Ga&&(c=yi(e),d=Rh(e).rc,Bi(this,e,d,c.querySelector(`.ob-smartfeed-joker[data-card-idx='${d}']`)));Sh(N,e)&&Th(N,!1,e);c=b;m&&(N.b[e].Pn&&Mi(h)?c||(c=M.ya(e),c.B().style.display="none",OBR.Lg.D(`empty_feed_${e}`,
[c])):N.b[e].Pn=!1);return{Ib:e,ze:k}}}}}Bc(a,b,c){Oi(b);this.Hf(b);Pi(a,c)}Hf(a){a.map(b=>{b=b.ja().ta;return M.ya(b)}).forEach(b=>{M.Hf(b,b.L())})}Sl(a,b){const c=Rh(a).rc,e=N.b[a].gz,d=M.B(b.ta);xi(d,"yellow");M.Sl(d,()=>Bi(this,a,c,d),{rootMargin:`${e}px 0px`})}la(){N.C()}};const nj=new mj;var oj=class{constructor(a){this.b=[];this.j=this.s.bind(this);this.j();this.Dc=a}observe(a){this.b.some(b=>b.La===a)||this.b.push({La:a,size:{height:a.clientHeight,width:a.clientWidth}})}unobserve(a){this.b=this.b.filter(b=>b.La!==a)}disconnect(){this.b=[]}s(){const a=this.b.filter(b=>{const c=b.La.clientHeight,e=b.La.clientWidth;if(b.size.height!==c||b.size.width!==e)return b.size.height=c,b.size.width=e,!0}).map(b=>b.La);0<a.length&&this.Dc(a);window.requestAnimationFrame(this.j)}};const pj=!!window.ResizeObserver;
var qj=class extends mj{constructor(){super()}b(a){var b=new ej(a);const {bh:c,Ib:e}=b.ja();var d=M.ya(e);d.Zr(c.length);OBR._jsc.Rb.mark(d,"mv","end",!0);Di(d);Xi(e);b=JSON.parse(b.ja().Kd);if(c&&0!==c.length){var f=!Xh(N,"feedManualChunkFetch",e),h=d.l("sideElementFeedLimiter",null),k=d.l("sideElementLimiterOffset",0),g=d.l("SideElementFeedLimiterFlow",null);d=document.querySelector(h);h=Ii(this,c,e);{const r=[];if(null===d)k=h;else{var l=Xh(N,"feedLayout",e);for(q of h){Wi(l,e,q);{var m=d;var p=
g;const v=M.B(e).parentNode,t=m.getBoundingClientRect(),x=v.getBoundingClientRect();m=p&&"copy-article-height"===p?m.clientHeight-v.clientHeight:t.bottom-x.bottom}if(m<-1*k){q.parentNode.removeChild(q);break}r.push(q)}k=r}}g=Si(c,k);Ji(k);Ki(g,e);this.Bc(c,g,e);if(k.length<h.length){if(g&&g.length){var q=g[g.length-1];Mh(b,e,q.ja())}a.cards=a.cards.slice(k?k.length:0);a&&a.cards&&Nh(e,a);!b||N.$h(e)||ai(N,e)||(this.De(d,e),$h(N,!0,e))}else q=g[g.length-1],a=[g[0],q],Mh(b,e,q.ja()),f&&b&&Li(this,e,
a);Sh(N,e)&&Th(N,!1,e)}else b&&Ni(this,e)}De(a,b){try{const c=a.offsetHeight,e=OBR.le(f=>{bi(N,b);for(let k of f)if((k.offsetHeight||k.contentRect.height)>1.1*c){d.unobserve(a);f=b;var h=N;h=f?h.b[f].nr:void 0;h?this.b(h):Bi(this,f,Oh(f),null)}},500),d=pj?new window.ResizeObserver(e):new oj(e);d.observe(a)}catch(c){OBR.logger.log(c)}}s(a,b){a={uf:lj(a,!0),Uc:b};return OBR._jsc.mb(a)}};const rj=new qj;OBR.Pe={init:a=>{const b=a.Qd.l("sideElementFeedLimiter",null);b&&document.querySelector(b)?ui(rj,a):ui(nj,a)},externalChunkLoad:a=>si(nj,a),yi:(a,b)=>zi(nj,a,b),la:()=>{nj.la();rj.la()}};OBR.o.W(OBR.o.v.Tg);}).call(window);
